### ISSUE TITLE
formatting is horrible

### ISSUE THREAD

**Issue by cristeigabriel** [KittenPopo/csgo-signatures#4]
as i've said, if you're going to store shit in plain text, at least apply something alike to clang-format's "AlignConsecutiveDeclaration"

**Comment by cristeigabriel** [comment]
or, programatically, you can also impose it like this
```
template<char delimiter = '.', uint32_t spacing = 55, typename... Args>
inline void
print_delimited(const char* lhs, const char* fmt, Args... args)
{
#ifdef _DEBUG
    assert(strlen(lhs) > 0 && strlen(lhs) < spacing);
    const uint32_t final_spacing = spacing - strlen(lhs);

    fputs(lhs, stdout);
    for (uint32_t i = 0; i < final_spacing; ++i) {
        fputc(delimiter, stdout);
    }

    printf(fmt, args...);
#endif
}
```

**Comment by KittenPopo** [comment]
I'm fine with not having the signature text's be aligned on the right, otherwise there's too big of a gap and it becomes harder to see which function lines up with what signature.

**Comment by cristeigabriel** [comment]
> I'm fine with not having the signature text's be aligned on the right, otherwise there's too big of a gap and it becomes harder to see which function lines up with what signature.

iterate through text, store the biggest string length, then in delimiter, at [biggest_string_length], instead of the 'delimiter' character, use something like the '<' sign, or make use of endline as is now.

**Comment by KittenPopo** [comment]
Formatting might be changed but for now it's fine.
